<a href="https://colab.research.google.com/github/rvssridatta/PythonSnippets/blob/main/numpytile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#tile function 


import  numpy as np

In [3]:
ar = np.arange(5)
ar

array([0, 1, 2, 3, 4])

In [4]:
print(ar)

[0 1 2 3 4]


In [5]:
repeat = 2

print("Repeating ar 2 times", np.tile(ar,repeat))

Repeating ar 2 times [0 1 2 3 4 0 1 2 3 4]


In [8]:
repeat = 3

print("Repeating ar 3 times: \n", np.tile(ar,repeat))

Repeating ar 3 times: 
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


In [16]:
ar = np.arange(3)
print(ar1)

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [17]:
a=2
b=2
repeat1 = (a,b)
ar1 = np.tile(ar,repeat1)
print("Repeating ar1 : \n", ar1)

Repeating ar1 : 
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [18]:
print("Repeating ar1 : \n", ar1.shape)

Repeating ar1 : 
 (2, 6)


In [28]:
a=3
b=2
repeat2 = (a,b)

ar2 = np.tile(ar,repeat2)
print("Repeating ar2: \n", ar2)
print("Repeating ar2: \n", ar2.shape)

Repeating ar2: 
 [[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]
Repeating ar2: 
 (3, 6)


In [29]:
a=2
b=3
repeat2 = (a,b)

ar2 = np.tile(ar,repeat2)
print("Repeating ar2: \n", ar2)
print("Repeating ar2: \n", ar2.shape)

Repeating ar2: 
 [[0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2]]
Repeating ar2: 
 (2, 9)


In [31]:
arr = np.arange(4).reshape(2, 2)
print("arr : \n", arr)
 
a = 2 
b = 1 
repetitions = (a, b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

a = 3
b = 2

repetitions = (a,b)
print("\nRepeating arr : \n", np.tile(arr, repetitions))
print("arr Shape : \n", np.tile(arr, repetitions).shape)

arr : 
 [[0 1]
 [2 3]]

Repeating arr : 
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]
arr Shape : 
 (4, 2)

Repeating arr : 
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]
arr Shape : 
 (6, 4)
