<a href="https://colab.research.google.com/github/rvssridatta/PythonSnippets/blob/main/expand_dims/expand_dims.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
x = np.array([4,2])
print(x)

[4 2]


In [8]:
print(x.shape)

(2,)


In [9]:
#The following is equivalent to x[np.newaxis, :] or x[np.newaxis]:

y = np.expand_dims(x, axis = 0)

In [10]:
y

array([[4, 2]])

In [11]:
y.shape

(1, 2)

In [14]:
y = np.expand_dims(x, axis = 1)
print(y)
y.shape

[[4]
 [2]]


(2, 1)

In [15]:
y = np.expand_dims(x, axis = (1,2))
print(y)
y.shape

[[[4]]

 [[2]]]


(2, 1, 1)

In [24]:
y = np.expand_dims(x, axis = (2,0,1))
print(y)
y.shape

[[[[4 2]]]]


(1, 1, 1, 2)

In [25]:
y = np.expand_dims(x, axis=(2, 0))
y


array([[[4],
        [2]]])

In [26]:
y.shape

(1, 2, 1)